In [38]:
#Started Sql Analysis

import sqlite3
import pandas as pd

In [39]:
#Creating a Database for our IPL Data
conn = sqlite3.connect("ipl.db")

#Importing Csv Files as dataframe using Pandas
matches = pd.read_csv('../data/matches.csv')
deliveries = pd.read_csv('../data/deliveries.csv')

In [40]:
#Cleaning Data 
matches['winner'] = matches['winner'].replace({ 'Kings XI Punjab':'Punjab Kings',
    'Delhi Daredevils':'Delhi Capitals',
    'Deccan Chargers':'Sunrisers Hyderabad',
    'Rising Pune Supergiant':'Rising Pune Supergiants',
    'Royal Challengers Bangalore': 'Royal Challengers Bengaluru'})

matches['season'] = matches['season'].replace({'2007/08':'2008','2009/10':'2010','2020/21':'2020'})

matches['venue'] = matches['venue'].str.split(',').str[0]
matches['venue'] = matches['venue'].replace({'M.Chinnaswamy Stadium':'M Chinnaswamy Stadium',
    'Punjab Cricket Association Stadium':'Maharaja Yadavindra Singh International Cricket Stadium',
    'Feroz Shah Kotla':'Arun Jaitley Stadium',
    'Sardar Patel Stadium':'Narendra Modi Stadium',
    'Zayed Cricket Stadium':'Sheikh Zayed Stadium'
    })


#Load Data into Sql Database

matches.to_sql('matches',conn,if_exists = 'replace',index = False)
deliveries.to_sql('deliveries',conn,if_exists = 'replace',index = False)

260920

## SQL Queries

In [41]:
#Finding Top 5 Teams with respect to total number of matches won

top_teams = pd.read_sql("""SELECT winner, COUNT(*) as total_wins
FROM matches
GROUP BY winner
ORDER BY total_wins DESC
LIMIT 5""",conn)
top_teams

                        winner  total_wins
0               Mumbai Indians         144
1          Chennai Super Kings         138
2        Kolkata Knight Riders         131
3  Royal Challengers Bengaluru         123
4          Sunrisers Hyderabad         117

In [42]:
#Finding Top Batsman with respect to runs scored

top_bat = pd.read_sql("""Select batter,sum(batsman_runs) as total_runs
FROM deliveries
GROUP BY batter
ORDER BY total_runs DESC
limit 10""",conn)
top_bat

           batter  total_runs
0         V Kohli        8014
1        S Dhawan        6769
2       RG Sharma        6630
3       DA Warner        6567
4        SK Raina        5536
5        MS Dhoni        5243
6  AB de Villiers        5181
7        CH Gayle        4997
8      RV Uthappa        4954
9      KD Karthik        4843